import random
import requests
from bs4 import BeautifulSoup
    
hardest_100 = [
    "Maximum Total Subarray Value II: https://leetcode.com/problems/maximum-total-subarray-value-ii",
    "Maximum Product of Subsequences With an Alternating Sum Equal to K: https://leetcode.com/problems/maximum-product-of-subsequences-with-an-alternating-sum-equal-to-k",
    "Smallest Divisible Digit Product II: https://leetcode.com/problems/smallest-divisible-digit-product-ii",
    "Final Array State After K Multiplication Operations II: https://leetcode.com/problems/final-array-state-after-k-multiplication-operations-ii",
    "Partition Array for Maximum XOR and AND: https://leetcode.com/problems/partition-array-for-maximum-xor-and-and",
    "Check If Digits Are Equal in String After Operations II: https://leetcode.com/problems/check-if-digits-are-equal-in-string-after-operations-ii",
    "Smallest Palindromic Rearrangement II: https://leetcode.com/problems/smallest-palindromic-rearrangement-ii",
    "Count Number of Trapezoids II: https://leetcode.com/problems/count-number-of-trapezoids-ii",
    "Minimum Moves to Reach Target in Grid: https://leetcode.com/problems/minimum-moves-to-reach-target-in-grid",
    "Find the Occurrence of First Almost Equal Substring: https://leetcode.com/problems/find-the-occurrence-of-first-almost-equal-substring",
    "Minimum Pair Removal to Sort Array II: https://leetcode.com/problems/minimum-pair-removal-to-sort-array-ii",
    "Select Cells in Grid With Maximum Score: https://leetcode.com/problems/select-cells-in-grid-with-maximum-score",
    "Maximum Sum of Subsequence With Non Adjacent Elements: https://leetcode.com/problems/maximum-sum-of-subsequence-with-non-adjacent-elements",
    "Strong Password Checker: https://leetcode.com/problems/strong-password-checker",
    "Longest Special Path II: https://leetcode.com/problems/longest-special-path-ii",
    "Maximize Count of Distinct Primes After Split: https://leetcode.com/problems/maximize-count-of-distinct-primes-after-split",
    "Lexicographically Smallest String After Adjacent Removals: https://leetcode.com/problems/lexicographically-smallest-string-after-adjacent-removals",
    "Maximum Value Sum by Placing Three Rooks I: https://leetcode.com/problems/maximum-value-sum-by-placing-three-rooks-i",
    "Minimum Reverse Operations: https://leetcode.com/problems/minimum-reverse-operations",
    "Find the Largest Palindrome Divisible by K: https://leetcode.com/problems/find-the-largest-palindrome-divisible-by-k",
    "Alternating Groups III: https://leetcode.com/problems/alternating-groups-iii",
    "Process String With Special Operations II: https://leetcode.com/problems/process-string-with-special-operations-ii",
    "Longest Palindrome After Substring Concatenation II: https://leetcode.com/problems/longest-palindrome-after-substring-concatenation-ii",
    "Find X Sum of All K Long Subarrays II: https://leetcode.com/problems/find-x-sum-of-all-k-long-subarrays-ii",
    "Minimize the Maximum Adjacent Element Difference: https://leetcode.com/problems/minimize-the-maximum-adjacent-element-difference",
    "Maximize Active Section With Trade II: https://leetcode.com/problems/maximize-active-section-with-trade-ii",
    "Frequencies of Shortest Supersequences: https://leetcode.com/problems/frequencies-of-shortest-supersequences",
    "Find Maximum Non Decreasing Array Length: https://leetcode.com/problems/find-maximum-non-decreasing-array-length",
    "Length of the Longest Increasing Path: https://leetcode.com/problems/length-of-the-longest-increasing-path",
    "Sum of Beautiful Subsequences: https://leetcode.com/problems/sum-of-beautiful-subsequences",
    "Block Placement Queries: https://leetcode.com/problems/block-placement-queries",
    "Fancy Sequence: https://leetcode.com/problems/fancy-sequence",
    "Minimum Cost to Equalize Array: https://leetcode.com/problems/minimum-cost-to-equalize-array",
    "Booking Concert Tickets in Groups: https://leetcode.com/problems/booking-concert-tickets-in-groups",
    "Minimum Operations to Equalize Binary String: https://leetcode.com/problems/minimum-operations-to-equalize-binary-string",
    "Minimum Stability Factor of Array: https://leetcode.com/problems/minimum-stability-factor-of-array",
    "Minimum Cost Path With Teleportations: https://leetcode.com/problems/minimum-cost-path-with-teleportations",
    "Subsequences With a Unique Middle Mode I: https://leetcode.com/problems/subsequences-with-a-unique-middle-mode-i",
    "Minimum Cost Good Caption: https://leetcode.com/problems/minimum-cost-good-caption",
    "Check If DFS Strings Are Palindromes: https://leetcode.com/problems/check-if-dfs-strings-are-palindromes",
    "Minimum Number of Valid Strings to Form Target II: https://leetcode.com/problems/minimum-number-of-valid-strings-to-form-target-ii",
    "Kth Smallest Amount With Single Denomination Combination: https://leetcode.com/problems/kth-smallest-amount-with-single-denomination-combination",
    "Construct String With Minimum Cost: https://leetcode.com/problems/construct-string-with-minimum-cost",
    "Find the Maximum Sequence Value of Array: https://leetcode.com/problems/find-the-maximum-sequence-value-of-array",
    "Smallest Substring With Identical Characters I: https://leetcode.com/problems/smallest-substring-with-identical-characters-i",
    "Maximize the Distance Between Points on a Square: https://leetcode.com/problems/maximize-the-distance-between-points-on-a-square",
    "Longest Palindromic Path in Graph: https://leetcode.com/problems/longest-palindromic-path-in-graph",
    "Threshold Majority Queries: https://leetcode.com/problems/threshold-majority-queries",
    "Separate Squares II: https://leetcode.com/problems/separate-squares-ii",
    "Trionic Array II: https://leetcode.com/problems/trionic-array-ii",
    "Sorted GCD Pair Queries: https://leetcode.com/problems/sorted-gcd-pair-queries",
    "Number of Integers With Popcount Depth Equal to K I: https://leetcode.com/problems/number-of-integers-with-popcount-depth-equal-to-k-i",
    "Number of Beautiful Integers in the Range: https://leetcode.com/problems/number-of-beautiful-integers-in-the-range",
    "Earliest Second to Mark Indices II: https://leetcode.com/problems/earliest-second-to-mark-indices-ii",
    "Equal Sum Grid Partition II: https://leetcode.com/problems/equal-sum-grid-partition-ii",
    "Longest Special Path: https://leetcode.com/problems/longest-special-path",
    "Maximize Subarray Sum After Removing All Occurrences of One Element: https://leetcode.com/problems/maximize-subarray-sum-after-removing-all-occurrences-of-one-element",
    "Maximum Profit From Trading Stocks With Discounts: https://leetcode.com/problems/maximum-profit-from-trading-stocks-with-discounts",
    "Minimum Moves to Pick K Ones: https://leetcode.com/problems/minimum-moves-to-pick-k-ones",
    "Maximum Total Reward Using Operations II: https://leetcode.com/problems/maximum-total-reward-using-operations-ii",
    "Count of Sub Multisets With Bounded Sum: https://leetcode.com/problems/count-of-sub-multisets-with-bounded-sum",
    "Number of Ways to Separate Numbers: https://leetcode.com/problems/number-of-ways-to-separate-numbers",
    "Maximum Area Rectangle With Point Constraints II: https://leetcode.com/problems/maximum-area-rectangle-with-point-constraints-ii",
    "Subarrays Distinct Element Sum of Squares II: https://leetcode.com/problems/subarrays-distinct-element-sum-of-squares-ii",
    "Count Binary Palindromic Numbers: https://leetcode.com/problems/count-binary-palindromic-numbers",
    "Count Substrings Divisible by Last Digit: https://leetcode.com/problems/count-substrings-divisible-by-last-digit",
    "Count Beautiful Numbers: https://leetcode.com/problems/count-beautiful-numbers",
    "Longest Common Prefix of K Strings After Removal: https://leetcode.com/problems/longest-common-prefix-of-k-strings-after-removal",
    "Valid Number: https://leetcode.com/problems/valid-number",
    "Count Non Decreasing Subarrays After K Operations: https://leetcode.com/problems/count-non-decreasing-subarrays-after-k-operations",
    "Count Substrings That Satisfy K Constraint II: https://leetcode.com/problems/count-substrings-that-satisfy-k-constraint-ii",
    "Partition Array Into Two Arrays to Minimize Sum Difference: https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference",
    "Count the Number of Houses at a Certain Distance II: https://leetcode.com/problems/count-the-number-of-houses-at-a-certain-distance-ii",
    "Shortest Matching Substring: https://leetcode.com/problems/shortest-matching-substring",
    "Maximum Number of Groups With Increasing Length: https://leetcode.com/problems/maximum-number-of-groups-with-increasing-length",
    "Find Products of Elements of Big Array: https://leetcode.com/problems/find-products-of-elements-of-big-array",
    "Maximize Subarray GCD Score: https://leetcode.com/problems/maximize-subarray-gcd-score",
    "Maximum and Minimum Sums of at Most Size K Subarrays: https://leetcode.com/problems/maximum-and-minimum-sums-of-at-most-size-k-subarrays",
    "Minimum Number of Visited Cells in a Grid: https://leetcode.com/problems/minimum-number-of-visited-cells-in-a-grid",
    "Number of Zigzag Arrays I: https://leetcode.com/problems/number-of-zigzag-arrays-i",
    "Find the Count of Monotonic Pairs II: https://leetcode.com/problems/find-the-count-of-monotonic-pairs-ii",
    "Path Existence Queries in a Graph II: https://leetcode.com/problems/path-existence-queries-in-a-graph-ii",
    "Palindrome Rearrangement Queries: https://leetcode.com/problems/palindrome-rearrangement-queries",
    "Find Weighted Median Node in Tree: https://leetcode.com/problems/find-weighted-median-node-in-tree",
    "Find the Sum of Subsequence Powers: https://leetcode.com/problems/find-the-sum-of-subsequence-powers",
    "Contains Duplicate III: https://leetcode.com/problems/contains-duplicate-iii",
    "Find the Maximum Length of a Good Subsequence II: https://leetcode.com/problems/find-the-maximum-length-of-a-good-subsequence-ii",
    "Find the Minimum Cost Array Permutation: https://leetcode.com/problems/find-the-minimum-cost-array-permutation",
    "Abbreviating the Product of a Range: https://leetcode.com/problems/abbreviating-the-product-of-a-range",
    "Next Special Palindrome Number: https://leetcode.com/problems/next-special-palindrome-number",
    "XOR After Range Multiplication Queries II: https://leetcode.com/problems/xor-after-range-multiplication-queries-ii",
    "Maximum Balanced Subsequence Sum: https://leetcode.com/problems/maximum-balanced-subsequence-sum",
    "Maximize the Minimum Game Score: https://leetcode.com/problems/maximize-the-minimum-game-score",
    "Count Beautiful Substrings II: https://leetcode.com/problems/count-beautiful-substrings-ii",
    "Find Substring With Given Hash Value: https://leetcode.com/problems/find-substring-with-given-hash-value",
    "Maximum Score From Grid Operations: https://leetcode.com/problems/maximum-score-from-grid-operations",
    "Minimum Operations to Make Character Frequencies Equal: https://leetcode.com/problems/minimum-operations-to-make-character-frequencies-equal",
    "Minimum Cost to Divide Array Into Subarrays: https://leetcode.com/problems/minimum-cost-to-divide-array-into-subarrays",
    "Check If the Rectangle Corner Is Reachable: https://leetcode.com/problems/check-if-the-rectangle-corner-is-reachable",
    "String Transformation: https://leetcode.com/problems/string-transformation"
]

selected_problems = random.sample(hardest_100, 3)

print(f"\033[1;38;2;128;0;0m\n    --- The Final 3: ---\n")

for problem in selected_problems:
    name, link = problem.split(": ", 1)
    print(f"\033[1;38;2;128;0;0m    {name}\033[0m: {link}")

print()