import { keywords } from "./pyInfo";

export const pythonMonarch = {
    defaultToken: "",
    tokenPostfix: ".python",
    keywords,
    brackets: [
        { open: "{", close: "}", token: "delimiter.curly" },
        { open: "[", close: "]", token: "delimiter.bracket" },
        { open: "(", close: ")", token: "delimiter.parenthesis" },
    ],
    tokenizer: {
        root: [
            [/[fF]"/, "string", "@fstring_double"],
            [/[fF]'/, "string", "@fstring_single"],
            [/"/, "string", "@string_double"],
            [/'/, "string", "@string_single"],
            [/(def)(\s+)([a-zA-Z_]\w*)/, ["keyword", "white", "entity.name.function"]],
            [/(class)(\s+)([a-zA-Z_]\w*)/, ["keyword", "white", "entity.name.class"]],
            [
                /\b(list|dict|set|tuple|int|str|float|bool|ListNode|TreeNode|TrieNode|List|Dict|Set|Tuple|Optional|Union|Any|Callable)\b/,
                "type",
            ],
            [
                /[a-zA-Z_]\w*(?=\()/,
                {
                    cases: {
                        list: "type",
                        dict: "type",
                        set: "type",
                        tuple: "type",
                        int: "type",
                        str: "type",
                        float: "type",
                        bool: "type",
                        ListNode: "type",
                        TreeNode: "type",
                        TrieNode: "type",
                        List: "type",
                        Dict: "type",
                        Set: "type",
                        Tuple: "type",
                        Optional: "type",
                        Union: "type",
                        Any: "type",
                        Callable: "type",
                        "@default": "entity.name.function",
                    },
                },
            ],
            [
                /[a-zA-Z_]\w*/,
                {
                    cases: {
                        return: "keyword.control",
                        if: "keyword.control",
                        elif: "keyword.control",
                        else: "keyword.control",
                        for: "keyword.control",
                        in: "keyword.control",
                        while: "keyword.control",
                        break: "keyword.control",
                        continue: "keyword.control",
                        try: "keyword.control",
                        except: "keyword.control",
                        finally: "keyword.control",
                        yield: "keyword.control",
                        with: "keyword.control",
                        as: "keyword.control",
                        raise: "keyword.control",
                        assert: "keyword.control",
                        import: "keyword.control",
                        from: "keyword.control",
                        pass: "keyword.control",

                        self: "variable.predefined",
                        True: "constant",
                        False: "constant",
                        None: "constant",

                        list: "type",
                        dict: "type",
                        set: "type",
                        tuple: "type",
                        List: "type",
                        Dict: "type",
                        Set: "type",
                        Tuple: "type",
                        Optional: "type",
                        Union: "type",
                        Any: "type",
                        Callable: "type",
                        int: "type",
                        str: "type",
                        float: "type",
                        bool: "type",
                        ListNode: "type",
                        TreeNode: "type",
                        TrieNode: "type",

                        "@keywords": "keyword",
                        "@default": "identifier",
                    },
                },
            ],
            { include: "@whitespace" },
            [/[{}()[\]]/, "@brackets"],
            [/[<>!%&^*\-+=|~]/, "operator"],
            [/\d+/, "number"],
            [/"([^"\\]|\\.)*$/, "string.invalid"],
            [/'([^'\\]|\\.)*$/, "string.invalid"],
        ],
        whitespace: [
            [/[ \t\r\n]+/, "white"],
            [/#.*$/, "comment"],
        ],
        string_double: [
            [/[^\\"]+/, "string"],
            [/\\./, "string.escape"],
            [/"/, "string", "@pop"],
        ],
        string_single: [
            [/[^\\']+/, "string"],
            [/\\./, "string.escape"],
            [/'/, "string", "@pop"],
        ],
        fstring_double: [
            [/{{/, "string"],
            [/}}/, "string"],
            [/{/, "delimiter.curly", "@fstring_expression"],
            [/[^\\"{}]+/, "string"],
            [/\\./, "string.escape"],
            [/"/, "string", "@pop"],
        ],
        fstring_single: [
            [/{{/, "string"],
            [/}}/, "string"],
            [/{/, "delimiter.curly", "@fstring_expression"],
            [/[^\\'{}]+/, "string"],
            [/\\./, "string.escape"],
            [/'/, "string", "@pop"],
        ],
        fstring_expression: [
            [/{/, "delimiter.curly", "@fstring_expression"],
            [/}/, "delimiter.curly", "@pop"],
            [
                /[a-zA-Z_]\w*/,
                {
                    cases: {
                        "@keywords": "keyword",
                        self: "variable.predefined",
                        True: "constant",
                        False: "constant",
                        None: "constant",
                        "@default": "identifier",
                    },
                },
            ],
            [/[()[\]]/, "@brackets"],
            [/[<>!%&^*\-+=|~:]/, "operator"],
            [/\d+/, "number"],
            [/".*?"/, "string"],
            [/'.*?'/, "string"],
            [/[ \t\r\n]+/, "white"],
        ],
    },
};
